<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f9b2cc6b-c1b8-4247-bd84-6568500e01f2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="26.7.0" />
  </ItemGroup>

</Project>
